package id.ac.poliban.mi.yusfan.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class PahlawanData {
    static List<Pahlawan> getAllPahlawan(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/VP_Hatta.jpg/330px-VP_Hatta.jpg", "Mohammad Hatta", "Dr. (H.C.) Drs. H. Mohammad Hatta (populer sebagai Bung Hatta; lahir dengan nama Mohammad Athar di Fort de Kock, Hindia Belanda, 12 Agustus 1902 – meninggal di Jakarta, 14 Maret 1980 pada umur 77 tahun) adalah negarawan dan ekonom Indonesia yang menjabat sebagai Wakil Presiden Indonesia pertama. Ia bersama Soekarno memainkan peranan sentral dalam perjuangan kemerdekaan Indonesia dari penjajahan Belanda sekaligus memproklamirkannya pada 17 Agustus 1945. Ia pernah menjabat sebagai Perdana Menteri dalam Kabinet Hatta I, Hatta II, dan RIS. Pada 1956, ia mundur dari jabatan wakil presiden karena berselisih dengan Presiden Soekarno. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Presiden_Sukarno.jpg/330px-Presiden_Sukarno.jpg", "Soekarno", "Dr.(H.C.) Ir. H. Soekarno1 (ER, EYD: Sukarno, nama lahir: Koesno Sosrodihardjo) (lahir di Surabaya, Jawa Timur, 6 Juni 1901 – meninggal di Jakarta, 21 Juni 1970 pada umur 69 tahun)[note 1][note 2] adalah Presiden pertama Republik Indonesia yang menjabat pada periode 1945–1967.[5]:11, 81 Ia memainkan peranan penting dalam memerdekakan bangsa Indonesia dari penjajahan Belanda.[6]:26-32 Ia adalah Proklamator Kemerdekaan Indonesia (bersama dengan Mohammad Hatta) yang terjadi pada tanggal 17 Agustus 1945. Soekarno adalah yang pertama kali mencetuskan konsep mengenai Pancasila sebagai dasar negara Indonesia dan ia sendiri yang menamainya."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/6/62/Mohammad_Yamin%2C_Pekan_Buku_Indonesia_1954%2C_p251.jpg", "Muhammad Yamin", "Prof. Mr. Mohammad Yamin, S.H. (lahir di Talawi, Sawahlunto, Sumatra Barat, 24 Agustus 1903 – meninggal di Jakarta, 17 Oktober 1962 pada umur 59 tahun) adalah sastrawan, sejarawan, budayawan, politikus, dan ahli hukum yang telah dihormati sebagai pahlawan nasional Indonesia. Ia merupakan salah satu perintis puisi modern Indonesia dan pelopor Sumpah Pemuda sekaligus \"pencipta imaji keindonesiaan\" yang mempengaruhi sejarah persatuan Indonesia.[1][2]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/300px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg", "Kartini", "Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi. Raden Adjeng Kartini berasal dari kalangan priyayi atau kelas bangsawan Jawa.[2] Ia merupakan putri dari Raden Mas Adipati Ario Sosroningrat, seorang patih yang diangkat menjadi bupati Jepara segera setelah Kartini lahir.[2] Kartini adalah putri dari istri pertama, tetapi bukan istri utama.[2] Ibunya bernama M.A. Ngasirah, putri dari Nyai Haji Siti Aminah dan Kyai Haji Madirono, seorang guru agama di Telukawur, Jepara.[2] Dari sisi ayahnya, silsilah Kartini dapat dilacak hingga Hamengkubuwana VI. Garis keturunan Bupati Sosroningrat bahkan dapat ditilik kembali ke istana Kerajaan Majapahit.[2] Semenjak Pangeran Dangirin menjadi bupati Surabaya pada abad ke-18, nenek moyang Sosroningrat mengisi banyak posisi penting di Pangreh Praja."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg", "Ki Hadjar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai Soewardi atau KHD) adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda. Tanggal kelahirannya sekarang diperingati di Indonesia sebagai Hari Pendidikan Nasional. Bagian dari semboyan ciptaannya, tut wuri handayani, menjadi slogan Kementerian Pendidikan Nasional Indonesia. Namanya diabadikan sebagai salah sebuah nama kapal perang Indonesia, KRI Ki Hajar Dewantara. Potret dirinya diabadikan pada uang kertas pecahan 20.000 rupiah tahun edisi 1998.[2] "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg", "Pattimura", "Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku. Menurut buku biografi Pattimura versi pemerintah yang pertama kali terbit, M Sapija menulis, Bahwa pahlawan Pattimura tergolong turunan bangsawan dan berasal dari Nusa Ina (Seram). Ayahnya yang bernama Antoni Matulessy adalah anak dari Kasimiliali Pattimura Mattulessy. Yang terakhir ini adalah putra raja Sahulau. Sahulau merupakan nama orang di negeri yang terletak dalam sebuah teluk di Seram. Namanya kini diabadikan untuk Universitas Pattimura, Kodam XVI/Pattimura dan Bandar Udara Pattimura di Ambon. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/2/2b/Tjoet_Nya%27_Dhien.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda. Pada tahun 1880, Cut Nyak Dhien menikah dengan Teuku Umar, setelah sebelumnya ia dijanjikan dapat ikut turun di medan perang jika menerima lamaran tersebut. Dari pernikahan ini Cut Nyak Dhien memiliki seorang anak yang diberi nama Cut Gambang[1]. Setelah pernikahannya dengan Teuku Umar, Cut Nyak Dhien bersama Teuku Umar bertempur bersama melawan Belanda. Namun, pada tanggal 11 Februari 1899 Teuku Umar gugur. Hal ini membuat Cut Nyak Dhien berjuang sendirian di pedalaman Meulaboh bersama pasukan kecilnya. Usia Cut Nyak Dien yang saat itu sudah relatif tua serta kondisi tubuh yang digrogoti berbagai penyakit seperti encok dan rabun membuat satu pasukannya yang bernama Pang Laot melaporkan keberadaannya karena iba.[2][3] Ia akhirnya ditangkap dan dibawa ke Banda Aceh. Di sana ia dirawat dan penyakitnya mulai sembuh. Keberadaan Cut Nyak Dhien yang dianggap masih memberikan pengaruh kuat terhadap perlawanan rakyat Aceh serta hubungannya dengan pejuang Aceh yang belum tertangkap membuatnya kemudian diasingkan ke Sumedang. Cut Nyak Dhien meninggal pada tanggal 6 November 1908 dan dimakamkan di Gunung Puyuh, Sumedang. Nama Cut Nyak Dhien kini diabadikan sebagai Bandar Udara Cut Nyak Dhien Nagan Raya di Meulaboh. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/c/c8/Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG/330px-Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG", "Pangeran Antasari", "Pangeran Antasari (lahir di Kayu Tangi, Kesultanan Banjar, 1797[1][2] atau 1809[3][4][5][6] – meninggal di Bayan Begok, Hindia Belanda, 11 Oktober 1862 pada umur 53 tahun) adalah seorang Pahlawan Nasional Indonesia. Ia adalah Sultan Banjar.[7] Pada 14 Maret 1862, dia dinobatkan sebagai pimpinan pemerintahan tertinggi di Kesultanan Banjar (Sultan Banjar) dengan menyandang gelar Panembahan Amiruddin Khalifatul Mukminin dihadapan para kepala suku Dayak dan adipati (gubernur) penguasa wilayah Dusun Atas, Kapuas dan Kahayan yaitu Tumenggung Surapati/Tumenggung Yang Pati Jaya Raja."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Diponegoro.jpg/330px-Diponegoro.jpg", "Diponegoro", "Bendara Pangeran Harya Dipanegara (lebih dikenal dengan nama Diponegoro, lahir di Ngayogyakarta Hadiningrat, 11 November 1785 – meninggal di Makassar, Hindia Belanda, 8 Januari 1855 pada umur 69 tahun) adalah salah seorang pahlawan nasional Republik Indonesia. Pangeran Diponegoro terkenal karena memimpin Perang Diponegoro/Perang Jawa (1825-1830) melawan pemerintah Hindia Belanda. Perang tersebut tercatat sebagai perang dengan korban paling besar dalam sejarah Indonesia. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hamengkubawono_IX_Official_Portrait.jpg/338px-Hamengkubawono_IX_Official_Portrait.jpg", "Hamengkubawana IX", "Sri Sultan Hamengkubuwana IX atau Gusti Raden Mas Dorodjatun (bahasa Jawa: Sri Sultan Hamengkubuwana IX, Hanacaraka: ꦯꦿꦶꦯꦸꦭ꧀ꦡꦟ꧀ꦲꦩꦼꦁ\u200Bꦑꦸꦨꦸꦮꦤ IX ), lahir di Ngayogyakarta Hadiningrat, 12 April 1912 – meninggal di Washington, DC, Amerika Serikat, 2 Oktober 1988 pada umur 76 tahun[a]) adalah seorang sultan yang pernah memimpin di Kesultanan Yogyakarta (1940–1988) dan Gubernur Daerah Istimewa Yogyakarta yang pertama setelah kemerdekaan Indonesia. Ia pernah menjabat sebagai Wakil Presiden Indonesia yang kedua antara tahun 1973 dan 1978. Dia juga dikenal sebagai Bapak Pramuka Indonesia, dan pernah menjabat sebagai Ketua Kwartir Nasional Gerakan Pramuka."));
        }
        return data;
    }
}
